# Generated by Django 3.2 on 2021-05-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fe_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_user', models.CharField(max_length=255)),
                ('fe_comment', models.CharField(max_length=500)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.comment')),
            ],
        ),
    ]
